### ISSUE TITLE
Standardizing behavior

### ISSUE THREAD

**Issue by thaliaarchi** [kspalaiologos/asm2ws#2]
I am building a universal Whitespace assembler, and as a part of that process have [documented](https://github.com/thaliaarchi/omniwsa/blob/main/docs/dialects/palaiologos.md) your Whitespace assembly dialect and found several parsing and integer range bugs. In reimplementing dialects, I effectively standardize the behavior and, since my implementation has bug-for-bug compatibility, that includes behavior that might be considered buggy. Would you be open to a PR fixing such bugs? If not, I understand.

**Comment by iczelia** [comment]
Yes, please.
